interface PatentRaw {
   狀態: string
   年度: string
   校內編號: string
   學院: string
   單位系所: string
   發明人: string
   共同發明人: string
   發明名稱: string
   發明名稱_英: string
   專利號碼: string
   專利權期間: string
   公告_獲證日期: string
   維護期程: string
   公告_獲證時間_西元: string
   維護期程_西元: string
   維護年度計: string
   領證年度: string
   到期月份: string
   申請日期: string
   申請年度: string
   申請案號: string
   專利類別: string
   專利國家: string
   方案: string
   資助單位: string
   計畫編號: string
   承辦事務所: string
   事務所聯絡人: string
   事務所檔號: string
   研發成果編號_STRIKE: string
   國科會編號_STRIKE: string
   專利已登錄: string
   國際專利分類號_IPC: string
   專利範圍: string
   技術成熟度_TRL: string
   技推委員會審理日期: string
   發明名稱_稿: string
   初評事務所: string
   申請專利範圍: string
   技術關鍵字: string
   進度: string
   費用: string
}

interface PatentTransformed {
   狀態: string
   年度: string
   校內編號: string
   學院: string
   單位系所: string
   發明人: string
   共同發明人: { name: string, contribution: number }[]
   發明名稱: string
   發明名稱_英: string
   專利號碼: string
   專利權期間: string
   公告_獲證日期: string
   維護期程: string
   公告_獲證時間_西元: string
   維護期程_西元: string
   維護年度計: string
   領證年度: string
   到期月份: string
   申請日期: string
   申請年度: string
   申請案號: string
   專利類別: string
   專利國家: string
   方案: string
   資助單位: string
   計畫編號: string
   承辦事務所: string
   事務所聯絡人: string
   事務所檔號: string
   研發成果編號_STRIKE: string
   國科會編號_STRIKE: string
   專利已登錄: string
   國際專利分類號_IPC: string
   專利範圍: string
   技術成熟度_TRL: string
   技推委員會審理日期: string
   發明名稱_稿: string
   初評事務所: string
   申請專利範圍: string
   技術關鍵字: string
   進度: string
   費用: string
}

export type { PatentRaw, PatentTransformed };
